# Generated by Django 5.1.2 on 2024-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_auto_reply',
            field=models.BooleanField(default=False),
        ),
    ]
