# Generated by Django 5.1.2 on 2024-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_reply_delay',
            field=models.IntegerField(default=0),
        ),
    ]
